apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-java-app
  template:
    metadata:
      labels:
        app: tomcat-java-app
    spec:
      containers:
      - name: tomcat-java-app
        image: REPOSITORY_URI:IMAGE_TAG
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-java-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tomcat-java-app
